# Site
name: '陪诊师创业联盟'
description: '陪诊知识经验分享、陪诊预约指南、异地就医陪诊、全程陪诊'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: ''
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    91peizhen:
      name:           91陪诊
      site:           http://www.qpeizhen.com
      avatar:         /assets/images/system/logo.png
      bio:            ""
      email:   
      wechat:           https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=Mzg4NDkwMzk4OA==&scene=124#wechat_redirect    

    peizhenshi:
      name:           陪诊师创业联盟
      site:           https://epeizhen.com
      avatar:         /assets/images/system/logo2.png
      bio:            ""
      email:   
      wechat:         https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=Mzg2Mzg3Njc4Nw==&scene=124#wechat_redirect     

   
   
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: peizhenshi
      avatar: /assets/images/system/logo2.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
